foursq_api:
  id: D0ZFMGQIMLGQFEO1XH5X3PSX1XNYHSXFNNAZYUWW0AKGZN2G
  secret: 4ZA303OWTNOOQHPEBSEP2YJKCG5EQOTD3R0UYNF4VVRISXWI

twitter_api:
  key: uwHnBH7vznFKpATuVBZpw 
  secret: GsahfiSIXaK0ag6IkDQfPCYANZYJvGPzsh51FWsqzA
  token: 1060965092-3os8VZTlBEhpW69RTLyHCHohCqunZNSmF7jOz5S
  token_secret: ynKIStntbXpxd0dSLWT6M217PONhLg3QOUjIUWka7mU
