foursquare_api:
  id: CH12EX0CVKXIP3D4GFEBGSKEOWX4LERUMZRSHBUH0NRKYUMY 
  secret: AZXWH21PYVZ5WSP1JJSN2NU5NI2NGHC5HPKKFKTITNWIAMUI
  redirect_url: http://staging.leavekudos.com/callback

tweeting:
  enabled: false

url_shortening:
  enabled: false 
