foursq_api:
  id: KIBNN41SBHFXRPYRY1V4GSXYSA2RSVQTKKWKBPG5N3I1OVMM 
  secret: FLP0ZNK1VQAJRPA320SVWM3S133OMQB1BNPXXWZO3A2XF5Q1

twitter_api:
  key: uwHnBH7vznFKpATuVBZpw
  secret: GsahfiSIXaK0ag6IkDQfPCYANZYJvGPzsh51FWsqzA
  token: 1060965092-3os8VZTlBEhpW69RTLyHCHohCqunZNSmF7jOz5S
  token_secret: ynKIStntbXpxd0dSLWT6M217PONhLg3QOUjIUWka7mU
