foursq_api:
  id: D0ZFMGQIMLGQFEO1XH5X3PSX1XNYHSXFNNAZYUWW0AKGZN2G
  secret: 4ZA303OWTNOOQHPEBSEP2YJKCG5EQOTD3R0UYNF4VVRISXWI
  redirect_url: http://localhost:3000/callback

tweeting:
  enabled: false
